### ISSUE TITLE
 The plugin has stopped working.

### ISSUE THREAD

**Issue by RE4ERKA** [Silthus/sInventoryKeeper#10]
When you start the server for the first time, the plugin in the list of plugins is red and gives an error in the console, but after restarting the plugins with the "/reload" command, the plugin starts working stably. Please fix.

Server core: PaperSpigot
Server version: 1.14.4

![image](https://user-images.githubusercontent.com/66727581/90335942-999d4a00-e002-11ea-98ab-eedbe2d642ea.png)
![image](https://user-images.githubusercontent.com/66727581/90335814-a5d4d780-e001-11ea-87c0-407b675060a1.png)

**Comment by Silthus** [comment]
Thank you for the bug report. I will look into it shortly and notify you as soon as I have a fix.

**Comment by Silthus** [comment]
I was not able to reproduce the issue, but can you please try this fix here anyways?

https://github.com/Silthus/sInventoryKeeper/releases/download/v3.2.1/sInventoryKeeper-3.2.1.jar

**Comment by RE4ERKA** [comment]
Nothing has changed = (. Maybe I can throw you the plugin configs?

**Comment by Silthus** [comment]
Yes that would help. Can you also send me the full startup log?

**Comment by RE4ERKA** [comment]
Here are the logs with starting the server and reloading plugins.
[latest.log](https://github.com/Silthus/sInventoryKeeper/files/5085698/latest.log)

All sInventoyKeeper configs.
[sinventorykeeper.zip](https://github.com/Silthus/sInventoryKeeper/files/5085719/sinventorykeeper.zip)

Hope this all helps.

**Comment by Silthus** [comment]
Ok thanks that helped!
It seems to come from an incompatibility with an other plugin you are using. However I am going to fix it on my side.
To make sure you could disable all other plugins temporarily and see if the error still occurs, which it shouldn't.

**Comment by Silthus** [comment]
Please try if this fixes it for you: https://github.com/Silthus/sInventoryKeeper/releases/download/v3.2.2/sInventoryKeeper-3.2.2.jar

And if it does and you like the plugin, you would really make my day wonderful if you leave a rating on Spigot :)

**Comment by RE4ERKA** [comment]
Just checked, the plugin works great. Thanks you.

I'm already.

![image](https://user-images.githubusercontent.com/66727581/90459377-5ab6e380-e12b-11ea-9581-ef2d244827fd.png)
